### ISSUE TITLE
`expected_output == False` for RMLTC0004b-CSV, while it should be `True`

### ISSUE THREAD

**Issue by thomas-delva** [kg-construct/rml-test-cases-support#8]
This results in a test failure for the RMLMapper, which produces the correct output but this the script interprets this as wrong because of the flag.

I think this comes from a mistake in the manifest graph.

**Comment by thomas-delva** [comment]
This seems to be a general issue with RMLTC0004b, as RMLTC0004b-MySQL also fails for the RMLMapper

**Comment by dachafra** [comment]
@thomas-delva should be this fixed in the original repo right than here?

**Comment by thomas-delva** [comment]
Yes I suppose it would :) 

I'll make a PR there changing the `metadata.*` files with this fix

**Comment by dachafra** [comment]
Awesome!

**Comment by thomas-delva** [comment]
I was too quick with this issue :)

`expected_output` should indeed be `False` since the term type of the subject map is declared as `rr:Literal`, leading to a malformed RML file

Reference: https://www.w3.org/TR/r2rml/#termtype

**Comment by dachafra** [comment]
thanks ;-)
