### ISSUE TITLE
RMLTC0007h-CSV: RMLMapper produces no file, expects empty file

### ISSUE THREAD

**Issue by thomas-delva** [kg-construct/rml-test-cases-support#9]
See title. This causes the test to be counted as a failure for the RMLMapper.

Not sure if this is strictly speaking a mistake in the script. Anyways, in the RMLMapper's CI producing no file is counted as okay for this test.

**Comment by thomas-delva** [comment]
This also occurs for RMLTC0002i-MySQL and RMLTC0002j-MySQL

**Comment by thomas-delva** [comment]
And for RMLTC0007h-MySQL. This seems to be a general issue for tests where failure is expected.

**Comment by dachafra** [comment]
The RMLTC0000 (https://rml.io/test-cases/#rmltc0000-csv) tests if with an empty input file and a correct mapping it generates an empty file. 7h (CSV/MySQL) test-cases should output an error parsing the mapping (a graph cannot be a Literal), and no file should be provided. In my opinion this should be solved at test-case level, not here. Expected error should be yes

In RMLTC0002i-MySQL and RMLTC0002j-MySQL mapping correct, expected error no, and empty file --> RMLMapper should generate an empty graph (as well as it does in RMLTC0000)

**Comment by thomas-delva** [comment]
I veriefied this and the issue is indeed with the test cases and/or their metadata, not with the script
